import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const colleges = [
  // ─── ENGINEERING ────────────────────────────────────────────
  {
    name: "IIT Bombay",
    slug: "iit-bombay",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=600&h=400&fit=crop&q=80",
    category: "Engineering",
    location: "Powai, Mumbai, Maharashtra",
    city: "Mumbai",
    state: "Maharashtra",
    type: "GOVERNMENT",
    annualFees: 211000,
    avgPackage: 21.8,
    placementRate: 95.0,
    rating: 4.9,
    totalReviews: 1240,
    ranking: 3,
    established: 1958,
    website: "https://iitb.ac.in",
    accreditation: "NAAC A++",
    description: "IIT Bombay is a premier public research university in Mumbai, renowned for engineering education, cutting-edge research, and strong industry connections.",
    programs: JSON.stringify(["Computer Science", "Electrical Engineering", "Mechanical Engineering", "Aerospace Engineering", "Data Science"]),
    facilities: JSON.stringify(["Main Library", "Hostels", "Gymkhana", "Convocation Hall", "HPC Center"]),
    courses: ["B.Tech Computer Science", "B.Tech Electrical Engineering", "M.Tech Computer Science", "MBA"],
  },
  {
    name: "IIT Madras",
    slug: "iit-madras",
    imageUrl: "https://images.unsplash.com/photo-1576495199011-eb94736d05d6?w=600&h=400&fit=crop&q=80",
    category: "Engineering",
    location: "Adyar, Chennai, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "GOVERNMENT",
    annualFees: 240000,
    avgPackage: 20.0,
    placementRate: 93.0,
    rating: 4.7,
    totalReviews: 1050,
    ranking: 2,
    established: 1959,
    website: "https://www.iitm.ac.in",
    accreditation: "NAAC A++",
    description: "IIT Madras is India's top-ranked institution (NIRF 2024), known for its forest campus, research excellence, and 200+ startups in its Research Park.",
    programs: JSON.stringify(["Computer Science", "Aerospace Engineering", "Data Science", "Electrical Engineering", "Ocean Engineering"]),
    facilities: JSON.stringify(["Central Library", "Research Park", "Student Wellness Centre", "Olympic Pool", "Deer Park"]),
    courses: ["B.Tech Computer Science", "B.Tech Aerospace", "B.S. Data Science (Online)", "M.Tech AI"],
  },
  {
    name: "IIT Delhi",
    slug: "iit-delhi",
    imageUrl: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=600&h=400&fit=crop&q=80",
    category: "Engineering",
    location: "Hauz Khas, New Delhi",
    city: "New Delhi",
    state: "Delhi",
    type: "GOVERNMENT",
    annualFees: 228000,
    avgPackage: 22.5,
    placementRate: 94.0,
    rating: 4.8,
    totalReviews: 1180,
    ranking: 4,
    established: 1961,
    website: "https://home.iitd.ac.in",
    accreditation: "NAAC A++",
    description: "IIT Delhi is among India's most prestigious engineering institutions, located in the heart of New Delhi with exceptional placements and research output.",
    programs: JSON.stringify(["Computer Science", "Electrical Engineering", "Textile Technology", "Chemical Engineering", "Mathematics"]),
    facilities: JSON.stringify(["Central Library", "Hostels", "SAC", "Swimming Pool", "Techfest Grounds"]),
    courses: ["B.Tech Computer Science", "B.Tech Electrical", "M.Tech AI", "MBA"],
  },
  {
    name: "IIT Kanpur",
    slug: "iit-kanpur",
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600&h=400&fit=crop&q=80",
    category: "Engineering",
    location: "Kanpur, Uttar Pradesh",
    city: "Kanpur",
    state: "Uttar Pradesh",
    type: "GOVERNMENT",
    annualFees: 222000,
    avgPackage: 18.5,
    placementRate: 88.0,
    rating: 4.6,
    totalReviews: 980,
    ranking: 5,
    established: 1959,
    website: "https://www.iitk.ac.in",
    accreditation: "NAAC A++",
    description: "IIT Kanpur is known for its strong focus on fundamental sciences, aerospace engineering, and being the pioneer of computer science education in India.",
    programs: JSON.stringify(["Computer Science", "Aerospace Engineering", "Physics", "Mathematics", "Industrial Engineering"]),
    facilities: JSON.stringify(["P.K. Kelkar Library", "Airstrip", "Research Labs", "Sports Complex", "Hostels"]),
    courses: ["B.Tech Computer Science", "B.Tech Aerospace", "M.Sc Physics", "Ph.D. Mathematics"],
  },
  {
    name: "NIT Trichy",
    slug: "nit-trichy",
    imageUrl: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=600&h=400&fit=crop&q=80",
    category: "Engineering",
    location: "Tiruchirappalli, Tamil Nadu",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    type: "GOVERNMENT",
    annualFees: 150000,
    avgPackage: 12.5,
    placementRate: 90.0,
    rating: 4.4,
    totalReviews: 1400,
    ranking: 9,
    established: 1964,
    website: "https://www.nitt.edu",
    accreditation: "NAAC A++",
    description: "NIT Trichy is the top-ranked NIT in India, known for excellent placements, vibrant campus life, and the famous Pragyan tech festival.",
    programs: JSON.stringify(["Computer Science", "Electronics", "Mechanical", "Civil Engineering", "Instrumentation"]),
    facilities: JSON.stringify(["Central Library", "Orion Hostels", "Gymkhana", "SAC", "Indoor Stadium"]),
    courses: ["B.Tech Computer Science", "B.Tech Electronics", "M.Tech VLSI", "MBA"],
  },
  {
    name: "BITS Pilani",
    slug: "bits-pilani",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=600&h=400&fit=crop&q=80",
    category: "Engineering",
    location: "Pilani, Rajasthan",
    city: "Pilani",
    state: "Rajasthan",
    type: "DEEMED",
    annualFees: 485000,
    avgPackage: 18.2,
    placementRate: 85.0,
    rating: 4.7,
    totalReviews: 1100,
    ranking: 20,
    established: 1964,
    website: "https://bits-pilani.ac.in",
    accreditation: "NAAC A",
    description: "BITS Pilani is a premier private deemed university, famous for its Practice School internship program and flexible dual-degree system.",
    programs: JSON.stringify(["Computer Science", "Electronics & Instrumentation", "Chemical Engineering", "Physics", "Economics"]),
    facilities: JSON.stringify(["BITS Library", "Student Activity Center", "Vyas Bhavan", "Medical Center", "Cricket Ground"]),
    courses: ["B.E. Computer Science", "B.E. Electronics", "M.Sc. Mathematics", "M.Tech AI"],
  },
  {
    name: "VIT Vellore",
    slug: "vit-vellore",
    imageUrl: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=600&h=400&fit=crop&q=80",
    category: "Engineering",
    location: "Vellore, Tamil Nadu",
    city: "Vellore",
    state: "Tamil Nadu",
    type: "PRIVATE",
    annualFees: 198000,
    avgPackage: 9.2,
    placementRate: 80.0,
    rating: 4.3,
    totalReviews: 2300,
    ranking: 11,
    established: 1984,
    website: "https://vit.ac.in",
    accreditation: "NAAC A++",
    description: "VIT Vellore is consistently ranked among India's top private engineering institutions with strong industry tie-ups and global partnerships.",
    programs: JSON.stringify(["Computer Science", "Information Technology", "Electronics & Communication", "Mechanical", "Biomedical"]),
    facilities: JSON.stringify(["Smart Classrooms", "Central Library", "Swimming Pool", "Hostels", "Food Courts"]),
    courses: ["B.Tech Computer Science", "B.Tech AI & ML", "B.Tech Electronics", "MBA"],
  },
  {
    name: "DTU Delhi",
    slug: "dtu-delhi",
    imageUrl: "https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=600&h=400&fit=crop&q=80",
    category: "Engineering",
    location: "Rohini, New Delhi",
    city: "New Delhi",
    state: "Delhi",
    type: "AUTONOMOUS",
    annualFees: 190000,
    avgPackage: 15.4,
    placementRate: 80.0,
    rating: 4.5,
    totalReviews: 950,
    ranking: 29,
    established: 1941,
    website: "https://dtu.ac.in",
    accreditation: "NAAC A+",
    description: "DTU (formerly Delhi College of Engineering) is one of India's oldest engineering colleges with a vibrant campus and excellent placement record.",
    programs: JSON.stringify(["Information Technology", "Software Engineering", "Mathematics & Computing", "Biotechnology", "Mechanical"]),
    facilities: JSON.stringify(["DCE Library", "Open Air Theatre", "Indoor Sports Complex", "Hostels", "Computer Center"]),
    courses: ["B.Tech Computer Science", "B.Tech Mathematics & Computing", "M.Tech Software Engineering", "MBA"],
  },
  {
    name: "MIT Manipal",
    slug: "mit-manipal",
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=400&fit=crop&q=80",
    category: "Engineering",
    location: "Manipal, Karnataka",
    city: "Manipal",
    state: "Karnataka",
    type: "PRIVATE",
    annualFees: 310000,
    avgPackage: 9.0,
    placementRate: 78.0,
    rating: 4.0,
    totalReviews: 1800,
    ranking: 22,
    established: 1957,
    website: "https://manipal.edu/mit.html",
    accreditation: "NAAC A+",
    description: "MIT Manipal is known for its cosmopolitan student body, international exposure, and strong alumni network in Silicon Valley.",
    programs: JSON.stringify(["Computer Science", "Mechanical", "Mechatronics", "Civil Engineering", "Biomedical"]),
    facilities: JSON.stringify(["MIT Library", "Innovation Centre", "Sports Complex", "Hostels", "Student Plaza"]),
    courses: ["B.Tech Computer Science", "B.Tech Mechatronics", "M.Tech Machine Learning"],
  },
  {
    name: "NIT Warangal",
    slug: "nit-warangal",
    imageUrl: "https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=600&h=400&fit=crop&q=80",
    category: "Engineering",
    location: "Warangal, Telangana",
    city: "Warangal",
    state: "Telangana",
    type: "GOVERNMENT",
    annualFees: 140000,
    avgPackage: 14.0,
    placementRate: 87.0,
    rating: 4.3,
    totalReviews: 1200,
    ranking: 12,
    established: 1959,
    website: "https://www.nitw.ac.in",
    accreditation: "NAAC A++",
    description: "NIT Warangal is one of the oldest and most reputed NITs, known for strong alumni network and Technozion, one of the largest tech fests in South India.",
    programs: JSON.stringify(["Computer Science", "Electronics", "Mechanical", "Chemical Engineering", "Biotechnology"]),
    facilities: JSON.stringify(["Central Library", "LHC Complex", "Indoor Stadium", "Hostels", "Research Labs"]),
    courses: ["B.Tech Computer Science", "B.Tech Electronics", "M.Tech Data Science", "Ph.D."],
  },

  // ─── SCIENCE ────────────────────────────────────────────
  {
    name: "IISc Bangalore",
    slug: "iisc-bangalore",
    imageUrl: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=600&h=400&fit=crop&q=80",
    category: "Science",
    location: "Bengaluru, Karnataka",
    city: "Bengaluru",
    state: "Karnataka",
    type: "GOVERNMENT",
    annualFees: 35000,
    avgPackage: 28.0,
    placementRate: 98.0,
    rating: 5.0,
    totalReviews: 800,
    ranking: 1,
    established: 1909,
    website: "https://iisc.ac.in",
    accreditation: "NAAC A++",
    description: "IISc is India's #1 ranked research university for science and engineering, founded by J.N. Tata. It leads the country in research publications and patents.",
    programs: JSON.stringify(["Physics", "Materials Engineering", "Aerospace Technology", "Neuroscience", "Computational Sciences"]),
    facilities: JSON.stringify(["J.R.D. Tata Library", "Supercomputing Facility", "Nanofabrication Centre", "Gymnasium"]),
    courses: ["B.S. Research Program", "M.Tech Computational Science", "Ph.D. Physics", "M.Des. Design"],
  },
  {
    name: "ISI Kolkata",
    slug: "isi-kolkata",
    imageUrl: "https://images.unsplash.com/photo-1535982330050-f1c2fb79ff78?w=600&h=400&fit=crop&q=80",
    category: "Science",
    location: "Baranagar, Kolkata, West Bengal",
    city: "Kolkata",
    state: "West Bengal",
    type: "GOVERNMENT",
    annualFees: 5000,
    avgPackage: 25.0,
    placementRate: 95.0,
    rating: 4.8,
    totalReviews: 420,
    ranking: 3,
    established: 1931,
    website: "https://www.isical.ac.in",
    accreditation: "NAAC A",
    description: "Indian Statistical Institute is a unique institution devoted to research, teaching and application of statistics, natural sciences and social sciences. Founded by P.C. Mahalanobis.",
    programs: JSON.stringify(["Statistics", "Mathematics", "Computer Science", "Quantitative Economics", "Quality Engineering"]),
    facilities: JSON.stringify(["R.A. Fisher Library", "Computing Lab", "Guest Houses", "Sports Grounds"]),
    courses: ["B.Stat", "B.Math", "M.Stat", "M.Tech Computer Science"],
  },

  // ─── MANAGEMENT ─────────────────────────────────────────
  {
    name: "IIM Ahmedabad",
    slug: "iim-ahmedabad",
    imageUrl: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=600&h=400&fit=crop&q=80",
    category: "Management",
    location: "Vastrapur, Ahmedabad, Gujarat",
    city: "Ahmedabad",
    state: "Gujarat",
    type: "GOVERNMENT",
    annualFees: 2400000,
    avgPackage: 35.0,
    placementRate: 100.0,
    rating: 4.9,
    totalReviews: 890,
    ranking: 1,
    established: 1961,
    website: "https://www.iima.ac.in",
    accreditation: "AACSB",
    description: "IIM Ahmedabad is India's most prestigious management school, consistently ranked #1 with its case-based pedagogy and elite alumni network.",
    programs: JSON.stringify(["Business Administration", "Finance", "Marketing", "Operations Management", "Entrepreneurship"]),
    facilities: JSON.stringify(["Louis Kahn Plaza", "Vikram Sarabhai Library", "Ravi J. Matthai Centre", "Swimming Pool", "Hostels"]),
    courses: ["PGP (MBA)", "Executive MBA", "Ph.D. Management"],
  },
  {
    name: "IIM Bangalore",
    slug: "iim-bangalore",
    imageUrl: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=600&h=400&fit=crop&q=80",
    category: "Management",
    location: "Bannerghatta Road, Bengaluru, Karnataka",
    city: "Bengaluru",
    state: "Karnataka",
    type: "GOVERNMENT",
    annualFees: 2450000,
    avgPackage: 33.8,
    placementRate: 100.0,
    rating: 4.8,
    totalReviews: 760,
    ranking: 2,
    established: 1973,
    website: "https://www.iimb.ac.in",
    accreditation: "AACSB, EQUIS",
    description: "IIM Bangalore is a globally recognized management school known for its analytics-driven approach, strong tech-sector placements, and beautiful campus.",
    programs: JSON.stringify(["Business Analytics", "Finance", "Strategy", "Marketing", "Digital Enterprise Management"]),
    facilities: JSON.stringify(["NSRCEL Incubator", "Management Library", "Auditorium", "Sports Complex"]),
    courses: ["PGP (MBA)", "PGPEM (Executive)", "Ph.D. Management"],
  },
  {
    name: "IIM Calcutta",
    slug: "iim-calcutta",
    imageUrl: "https://images.unsplash.com/photo-1606761568499-6d2451b23c66?w=600&h=400&fit=crop&q=80",
    category: "Management",
    location: "Joka, Kolkata, West Bengal",
    city: "Kolkata",
    state: "West Bengal",
    type: "GOVERNMENT",
    annualFees: 2300000,
    avgPackage: 35.0,
    placementRate: 100.0,
    rating: 4.8,
    totalReviews: 680,
    ranking: 3,
    established: 1961,
    website: "https://www.iimcal.ac.in",
    accreditation: "AACSB, EQUIS",
    description: "IIM Calcutta is India's first IIM and the oldest management institution in Asia. Known for rigorous academics and the highest median salary among IIMs.",
    programs: JSON.stringify(["Finance", "Marketing", "Strategy", "Operations", "MIS"]),
    facilities: JSON.stringify(["B.C. Roy Library", "Auditorium", "Lake Campus", "Hostels", "Sports Complex"]),
    courses: ["PGDM (MBA)", "MBAEx", "Ph.D. Finance"],
  },
  {
    name: "XLRI Jamshedpur",
    slug: "xlri-jamshedpur",
    imageUrl: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=600&h=400&fit=crop&q=80",
    category: "Management",
    location: "Jamshedpur, Jharkhand",
    city: "Jamshedpur",
    state: "Jharkhand",
    type: "PRIVATE",
    annualFees: 2600000,
    avgPackage: 30.2,
    placementRate: 100.0,
    rating: 4.7,
    totalReviews: 540,
    ranking: 6,
    established: 1949,
    website: "https://www.xlri.ac.in",
    accreditation: "AACSB",
    description: "XLRI is India's oldest B-school, renowned for HR management. Its alumni dominate India's corporate HR landscape across Fortune 500 companies.",
    programs: JSON.stringify(["Human Resources", "Business Management", "General Management", "Finance"]),
    facilities: JSON.stringify(["Library", "Tata Auditorium", "Sports Grounds", "Hostel Complex"]),
    courses: ["PGDM HRM", "PGDM BM", "Executive PGDM"],
  },

  // ─── MEDICAL ────────────────────────────────────────────
  {
    name: "AIIMS Delhi",
    slug: "aiims-delhi",
    imageUrl: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&h=400&fit=crop&q=80",
    category: "Medical",
    location: "Ansari Nagar, New Delhi",
    city: "New Delhi",
    state: "Delhi",
    type: "GOVERNMENT",
    annualFees: 10000,
    avgPackage: 18.0,
    placementRate: 100.0,
    rating: 4.8,
    totalReviews: 650,
    ranking: 1,
    established: 1956,
    website: "https://www.aiims.edu",
    accreditation: "MCI Approved",
    description: "AIIMS Delhi is India's apex medical institution, setting benchmarks in medical education and patient care with government-subsidized fees.",
    programs: JSON.stringify(["MBBS", "MD General Medicine", "MS Surgery", "B.Sc Nursing", "M.Sc Biochemistry"]),
    facilities: JSON.stringify(["Dr. B.B. Dikshit Library", "1000-bed Hospital", "Trauma Centre", "Research Labs", "Hostels"]),
    courses: ["MBBS", "MD General Medicine", "MS Surgery", "B.Sc Nursing"],
  },
  {
    name: "CMC Vellore",
    slug: "cmc-vellore",
    imageUrl: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600&h=400&fit=crop&q=80",
    category: "Medical",
    location: "Vellore, Tamil Nadu",
    city: "Vellore",
    state: "Tamil Nadu",
    type: "PRIVATE",
    annualFees: 65000,
    avgPackage: 15.0,
    placementRate: 100.0,
    rating: 4.7,
    totalReviews: 520,
    ranking: 2,
    established: 1900,
    website: "https://www.cmch-vellore.edu",
    accreditation: "NAAC A++",
    description: "CMC Vellore is one of India's most reputed medical colleges, known for its missionary spirit, affordable treatment, and pioneering surgeries.",
    programs: JSON.stringify(["MBBS", "MD Paediatrics", "MS Orthopaedics", "B.Sc Nursing", "Allied Health Sciences"]),
    facilities: JSON.stringify(["2200-bed Hospital", "Rehab Centre", "Research Institute", "Library", "Hostels"]),
    courses: ["MBBS", "MD Paediatrics", "MS Orthopaedics", "B.Sc Allied Health"],
  },
  {
    name: "JIPMER Puducherry",
    slug: "jipmer-puducherry",
    imageUrl: "https://images.unsplash.com/photo-1551076805-e1869033e561?w=600&h=400&fit=crop&q=80",
    category: "Medical",
    location: "Puducherry",
    city: "Puducherry",
    state: "Tamil Nadu",
    type: "GOVERNMENT",
    annualFees: 8000,
    avgPackage: 14.0,
    placementRate: 100.0,
    rating: 4.6,
    totalReviews: 380,
    ranking: 4,
    established: 1823,
    website: "https://jipmer.edu.in",
    accreditation: "NAAC A++",
    description: "JIPMER is one of India's oldest and most prestigious medical institutions, offering nearly free medical education with cutting-edge research facilities.",
    programs: JSON.stringify(["MBBS", "MD Pathology", "MS General Surgery", "M.Sc Physiology", "Ph.D. Medical Sciences"]),
    facilities: JSON.stringify(["2500-bed Hospital", "Simulation Lab", "Central Library", "Research Block", "Hostels"]),
    courses: ["MBBS", "MD Pathology", "MS General Surgery", "Ph.D."],
  },
  {
    name: "MAMC Delhi",
    slug: "mamc-delhi",
    imageUrl: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&h=400&fit=crop&q=80",
    category: "Medical",
    location: "Bahadur Shah Zafar Marg, New Delhi",
    city: "New Delhi",
    state: "Delhi",
    type: "GOVERNMENT",
    annualFees: 15000,
    avgPackage: 12.0,
    placementRate: 95.0,
    rating: 4.5,
    totalReviews: 340,
    ranking: 5,
    established: 1958,
    website: "https://www.mamc.ac.in",
    accreditation: "MCI Approved",
    description: "Maulana Azad Medical College is among Delhi's top government medical colleges, attached to Lok Nayak Hospital with excellent clinical exposure.",
    programs: JSON.stringify(["MBBS", "MD Medicine", "MS Surgery", "MD Radiology", "MD Anaesthesiology"]),
    facilities: JSON.stringify(["Lok Nayak Hospital", "Central Library", "Anatomy Museum", "Hostels"]),
    courses: ["MBBS", "MD Medicine", "MS Surgery", "MD Radiology"],
  },

  // ─── ARTS & HUMANITIES ──────────────────────────────────
  {
    name: "Delhi University",
    slug: "delhi-university",
    imageUrl: "https://images.unsplash.com/photo-1568792923760-d70635a89fdc?w=600&h=400&fit=crop&q=80",
    category: "Arts",
    location: "North Campus, New Delhi",
    city: "New Delhi",
    state: "Delhi",
    type: "GOVERNMENT",
    annualFees: 25000,
    avgPackage: 6.5,
    placementRate: 70.0,
    rating: 4.2,
    totalReviews: 3200,
    ranking: 11,
    established: 1922,
    website: "https://www.du.ac.in",
    accreditation: "NAAC A++",
    description: "University of Delhi offers a wide range of programs across humanities, sciences, and commerce through its 90+ affiliated colleges.",
    programs: JSON.stringify(["Economics", "Political Science", "English Literature", "Commerce", "Mathematics"]),
    facilities: JSON.stringify(["Central Library", "North Campus Grounds", "Conference Halls", "Hostels", "Student Union"]),
    courses: ["B.A. Economics (Hons)", "B.Com (Hons)", "B.Sc Mathematics", "M.A. English"],
  },
  {
    name: "JNU Delhi",
    slug: "jnu-delhi",
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600&h=400&fit=crop&q=80",
    category: "Arts",
    location: "New Mehrauli Road, New Delhi",
    city: "New Delhi",
    state: "Delhi",
    type: "GOVERNMENT",
    annualFees: 12000,
    avgPackage: 5.5,
    placementRate: 65.0,
    rating: 4.3,
    totalReviews: 1800,
    ranking: 6,
    established: 1969,
    website: "https://www.jnu.ac.in",
    accreditation: "NAAC A++",
    description: "Jawaharlal Nehru University is India's premier liberal arts and social sciences university, known for its research excellence and affordable education.",
    programs: JSON.stringify(["International Relations", "Political Science", "Languages", "Environmental Sciences", "Social Medicine"]),
    facilities: JSON.stringify(["Central Library", "Language Labs", "Parthasarathy Rocks", "Hostels", "Amphitheatre"]),
    courses: ["M.A. International Relations", "M.A. Political Science", "M.Phil. Linguistics", "Ph.D."],
  },
  {
    name: "BHU Varanasi",
    slug: "bhu-varanasi",
    imageUrl: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=600&h=400&fit=crop&q=80",
    category: "Arts",
    location: "Lanka, Varanasi, Uttar Pradesh",
    city: "Varanasi",
    state: "Uttar Pradesh",
    type: "GOVERNMENT",
    annualFees: 18000,
    avgPackage: 5.0,
    placementRate: 60.0,
    rating: 4.1,
    totalReviews: 2800,
    ranking: 8,
    established: 1916,
    website: "https://www.bhu.ac.in",
    accreditation: "NAAC A",
    description: "Banaras Hindu University is one of Asia's largest residential universities, founded by Madan Mohan Malaviya, offering 300+ courses.",
    programs: JSON.stringify(["Sanskrit", "Hindi Literature", "Ancient History", "Philosophy", "Fine Arts"]),
    facilities: JSON.stringify(["Sayaji Rao Library", "Bharat Kala Bhavan Museum", "Hospital", "Sports Grounds", "Temple"]),
    courses: ["B.A. Sanskrit", "B.A. History", "M.A. Philosophy", "M.F.A. Fine Arts"],
  },

  // ─── LAW ────────────────────────────────────────────────
  {
    name: "NLSIU Bangalore",
    slug: "nlsiu-bangalore",
    imageUrl: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&h=400&fit=crop&q=80",
    category: "Law",
    location: "Nagarbhavi, Bengaluru, Karnataka",
    city: "Bengaluru",
    state: "Karnataka",
    type: "GOVERNMENT",
    annualFees: 230000,
    avgPackage: 22.0,
    placementRate: 95.0,
    rating: 4.9,
    totalReviews: 420,
    ranking: 1,
    established: 1987,
    website: "https://www.nls.ac.in",
    accreditation: "BCI Approved",
    description: "National Law School of India University is India's top law school, pioneer of the 5-year integrated law program, and producer of Supreme Court advocates and corporate lawyers.",
    programs: JSON.stringify(["Constitutional Law", "Corporate Law", "International Law", "Criminal Law", "IP Law"]),
    facilities: JSON.stringify(["Law Library", "Moot Court Hall", "IT Lab", "Hostels", "Auditorium"]),
    courses: ["B.A. LL.B (Hons)", "LL.M.", "Ph.D. Law"],
  },
  {
    name: "NALSAR Hyderabad",
    slug: "nalsar-hyderabad",
    imageUrl: "https://images.unsplash.com/photo-1505664194779-8beaceb93744?w=600&h=400&fit=crop&q=80",
    category: "Law",
    location: "Shameerpet, Hyderabad, Telangana",
    city: "Hyderabad",
    state: "Telangana",
    type: "GOVERNMENT",
    annualFees: 250000,
    avgPackage: 20.0,
    placementRate: 92.0,
    rating: 4.7,
    totalReviews: 350,
    ranking: 2,
    established: 1998,
    website: "https://www.nalsar.ac.in",
    accreditation: "BCI Approved",
    description: "NALSAR University of Law is one of India's top 3 NLUs, known for its strong moot court culture and consistently high placements in top law firms.",
    programs: JSON.stringify(["Corporate Law", "Constitutional Law", "Intellectual Property", "Human Rights Law"]),
    facilities: JSON.stringify(["Law Library", "Moot Court", "Hostels", "Sports Complex"]),
    courses: ["B.A. LL.B (Hons)", "LL.M.", "Ph.D. Law"],
  },
  {
    name: "NLU Delhi",
    slug: "nlu-delhi",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=400&fit=crop&q=80",
    category: "Law",
    location: "Sector 14, Dwarka, New Delhi",
    city: "New Delhi",
    state: "Delhi",
    type: "GOVERNMENT",
    annualFees: 215000,
    avgPackage: 19.0,
    placementRate: 90.0,
    rating: 4.6,
    totalReviews: 300,
    ranking: 3,
    established: 2008,
    website: "https://nludelhi.ac.in",
    accreditation: "BCI Approved",
    description: "National Law University Delhi has quickly risen to become one of India's top 3 law schools, known for its Delhi advantage in internships and judicial clerkships.",
    programs: JSON.stringify(["Corporate Law", "Environmental Law", "Criminal Law", "Tax Law", "Arbitration"]),
    facilities: JSON.stringify(["Central Library", "Moot Court Hall", "Computer Lab", "Hostels"]),
    courses: ["B.A. LL.B (Hons)", "LL.M.", "Ph.D. Law"],
  },

  // ─── DESIGN ─────────────────────────────────────────────
  {
    name: "NID Ahmedabad",
    slug: "nid-ahmedabad",
    imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&h=400&fit=crop&q=80",
    category: "Design",
    location: "Paldi, Ahmedabad, Gujarat",
    city: "Ahmedabad",
    state: "Gujarat",
    type: "GOVERNMENT",
    annualFees: 380000,
    avgPackage: 14.0,
    placementRate: 85.0,
    rating: 4.6,
    totalReviews: 290,
    ranking: 1,
    established: 1961,
    website: "https://www.nid.edu",
    accreditation: "NIRF Top Design",
    description: "National Institute of Design is India's premier design institution, founded on the recommendation of Charles and Ray Eames. It shaped Indian design education.",
    programs: JSON.stringify(["Product Design", "Communication Design", "Textile Design", "Animation", "UX Design"]),
    facilities: JSON.stringify(["Design Studios", "Workshop", "Material Library", "Gallery", "Hostels"]),
    courses: ["B.Des Product Design", "B.Des Communication", "M.Des Interaction Design"],
  },

  // ─── COMMERCE ───────────────────────────────────────────
  {
    name: "SRCC Delhi",
    slug: "srcc-delhi",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=600&h=400&fit=crop&q=80",
    category: "Commerce",
    location: "North Campus, University of Delhi",
    city: "New Delhi",
    state: "Delhi",
    type: "GOVERNMENT",
    annualFees: 32000,
    avgPackage: 14.0,
    placementRate: 88.0,
    rating: 4.7,
    totalReviews: 1600,
    ranking: 1,
    established: 1926,
    website: "https://www.srcc.edu",
    accreditation: "NAAC A++",
    description: "Shri Ram College of Commerce is India's most prestigious commerce college, producing India's top bankers, chartered accountants, and business leaders.",
    programs: JSON.stringify(["Commerce", "Economics", "Mathematics", "Business Studies"]),
    facilities: JSON.stringify(["Library", "Auditorium", "Seminar Halls", "Sports Grounds"]),
    courses: ["B.Com (Hons)", "B.A. Economics (Hons)", "M.Com"],
  },

  // ─── ADDITIONAL ENGINEERING ─────────────────────────────
  {
    name: "IIT Kharagpur",
    slug: "iit-kharagpur",
    imageUrl: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=600&h=400&fit=crop&q=80",
    category: "Engineering",
    location: "Kharagpur, West Bengal",
    city: "Kharagpur",
    state: "West Bengal",
    type: "GOVERNMENT",
    annualFees: 220000,
    avgPackage: 19.0,
    placementRate: 90.0,
    rating: 4.7,
    totalReviews: 1100,
    ranking: 6,
    established: 1951,
    website: "https://www.iitkgp.ac.in",
    accreditation: "NAAC A++",
    description: "IIT Kharagpur is India's oldest IIT with the largest campus. Known for its diverse departments, Spring Fest, and producing Sundar Pichai.",
    programs: JSON.stringify(["Computer Science", "Electronics", "Mechanical", "Architecture", "Agricultural Engineering"]),
    facilities: JSON.stringify(["Central Library", "Technology Market", "Gymkhana", "Guest Houses", "1600-acre Campus"]),
    courses: ["B.Tech Computer Science", "B.Arch", "M.Tech AI", "MBA"],
  },
  {
    name: "IIT Roorkee",
    slug: "iit-roorkee",
    imageUrl: "https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=600&h=400&fit=crop&q=80",
    category: "Engineering",
    location: "Roorkee, Uttarakhand",
    city: "Roorkee",
    state: "Uttarakhand",
    type: "GOVERNMENT",
    annualFees: 215000,
    avgPackage: 17.5,
    placementRate: 87.0,
    rating: 4.5,
    totalReviews: 920,
    ranking: 7,
    established: 1847,
    website: "https://www.iitr.ac.in",
    accreditation: "NAAC A++",
    description: "IIT Roorkee is Asia's oldest technical institution (est. 1847), formerly known as Thomason College of Civil Engineering, with exceptional civil and water engineering programs.",
    programs: JSON.stringify(["Civil Engineering", "Hydrology", "Computer Science", "Architecture", "Earthquake Engineering"]),
    facilities: JSON.stringify(["Mahatma Gandhi Library", "Heritage Buildings", "Water Resources Lab", "Hostels"]),
    courses: ["B.Tech Civil Engineering", "B.Tech Computer Science", "M.Tech Earthquake Engineering", "B.Arch"],
  },
];

async function main() {
  console.log("🌱 Seeding database...");

  // Clean slate
  await prisma.savedCollege.deleteMany({});
  await prisma.course.deleteMany({});
  await prisma.college.deleteMany({});

  for (const college of colleges) {
    const { courses, ...collegeData } = college;

    // Create college
    const created = await prisma.college.create({
      data: collegeData,
    });

    // Create courses
    await prisma.course.createMany({
      data: courses.map((name: string) => ({
        name,
        collegeId: created.id,
      })),
    });

    console.log(`✅ ${created.name}`);
  }

  console.log(`🎉 Seeding complete! ${colleges.length} colleges added.`);
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });